# Generated by Django 4.0.3 on 2022-03-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=19)),
                ('user_id', models.IntegerField()),
                ('topic', models.CharField(max_length=20)),
                ('application_id', models.IntegerField()),
                ('attemps', models.PositiveIntegerField()),
                ('sent', models.DateTimeField()),
                ('received', models.DateTimeField()),
            ],
        ),
    ]
