# Generated by Django 4.0.3 on 2022-03-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
