# Generated by Django 4.0.3 on 2022-03-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='application_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
