# Generated by Django 4.0.3 on 2022-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='application_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
