# Generated by Django 4.0.3 on 2022-03-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
