# Generated by Django 4.0.3 on 2022-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='application_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='received',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='resource',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
