# Generated by Django 4.0.3 on 2022-03-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_application_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='attemps',
            new_name='attempts',
        ),
    ]
